languageCode: 'fr'
title: POC - Hugo on shared host
theme: 'simple-onepage-and-gallery'
baseURL:
removePathAccents: true


menu:
  main:
    - name: Accueil
      pre: home
      url: "/"
      weight: 1
    
taxonomies:
