# Created from 
# https://github.com/noesya/bordeauxmontaigne-iut/blob/main/.github/workflows/deploy.yml

# Environment vars to set on github:
# HUGO_VERSION
# HUGO_ENV
# SSH_PRIVATE_KEY
# SSH_USER
# SSH_HOST
# SSH_PORT
# SSH_WORKDIR

name: Build and Deploy production on server

on:
  push:
    branches:
      - production  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ secrets.HUGO_VERSION }}
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v3
        continue-on-error: true
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install JS dependencies
        continue-on-error: true
        run: yarn install --frozen-lockfile

      - name: Build
        run: hugo -e ${{ secrets.HUGO_ENV }} --minify

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      # - name: Adding Known Hosts
      #   continue-on-error: true
      #   run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # - name: Deploy with rsync
      #   run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_WORKDIR }}/

      - name: Test
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls